### ISSUE TITLE
Error when trying to generate humanized VRM rig

### ISSUE THREAD

**Issue by thebuddyadrian** [nanoskript/vrm-rigify#1]
I got this error using the "Generate Humanized VRM rig" command. I'm using a model exported from VRoid Studio 1.19.0. I'm not sure what version of VRM VRoid uses, but if it's using VRM 1.0, maybe that's the problem?

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\thebu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm_rigify\__init__.py", line 42, in execute
    meta_rig = meta.generate_meta_rig(vroid_rig)
  File "C:\Users\thebu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm_rigify\meta.py", line 55, in generate_meta_rig
    position_meta_rig(meta_rig, vroid_rig)
  File "C:\Users\thebu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm_rigify\meta.py", line 35, in position_meta_rig
    conversions = create_bone_mapping(base_bones, vroid_rig)
  File "C:\Users\thebu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\vrm_rigify\base.py", line 111, in create_bone_mapping
    assert vroid_matches, f"no VRoid bones found for `{vroid_pattern}`"
AssertionError: no VRoid bones found for `^Index3_end`
```
![image](https://user-images.githubusercontent.com/8119394/210907284-6a673837-d9da-4139-adac-202a6fc9d2d4.png)

**Comment by nanoskript** [comment]
Thanks for opening an issue :)

It looks like at some point, VRoid Studio stopped including the `_end` bones, so now there is now one less bone for each finger. If you need a quick fix until I update the addon, you can add this string:
```python
    '[a-zA-Z_-].03.[LR]',
```
to the arrays `META_IGNORED` and `BONES_DELETE`, both inside of `meta.py`.

**Comment by nanoskript** [comment]
Fixed (along with finger bone positioning) in https://github.com/nanoskript/vrm-rigify/commit/ca8555fe7474b0e77a44c2f886d830bad5337dd3.
